---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-storage"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "200Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/rancher/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"