apiVersion: v1
kind: Service
metadata:
  name: dnd-5e-tools
  labels:
    app: dnd-5e-tools
spec:
  selector:
    app: dnd-5e-tools
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
