apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-tls-certificate
  namespace: kube-system
spec:
  # Secret names are always required.
  secretName: default-local-tls

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  # secretTemplate:
  #   annotations:
  #     my-secret-annotation-1: "foo"
  #     my-secret-annotation-2: "bar"
  #   labels:
  #     my-secret-label: foo

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - lshadler@homelab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - argo.ls.local
    - traefik.ls.local
    - code.ls.local
    - media.ls.local
  # Issuer references are always required.
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer