apiVersion: traefik.containo.us/v1alpha1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    kubernetes.io/ingress.class: traefik
spec:
  rules:
     - host: "argo.ls.local"
       http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: argocd-server
                 port:
                   number: 80
  tls:
    - secretName: argo-local-tls