---
# Source: coder/templates/coder.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-server-sa
  namespace: code-server
---
# Source: coder/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: code-server-workspace-perms
  namespace: code-server
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["*"]
---
# Source: coder/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-server-sa-bind
  namespace: code-server
subjects:
  - kind: ServiceAccount
    name: code-server-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: code-server-workspace-perms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: code-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: code-server
      tier: frontend
  template:
    metadata:
      labels:
        app: code-server
        tier: frontend
    spec:
      serviceAccountName: code-server-sa
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - image: ghcr.io/coder/coder:v0.8.14
        imagePullPolicy: IfNotPresent
        name: code-server
        ports:
          - name: "http"
            containerPort: 8080
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v2/buildinfo
            port: "http"
            scheme: "HTTP"
        livenessProbe:
          httpGet:
            path: /api/v2/buildinfo
            port: "http"
            scheme: "HTTP"
        env:
          - name: CODER_PG_CONNECTION_URL
            value: "postgresql://username:password@code-server/code-db.code-server.svc.cluster.local?sslmode=disable"
          - name: CODER_ADDRESS
            value: "0.0.0.0:8080"
          # You'll need to set CODER_ACCESS_URL to an IP or domain
          # that workspaces can reach. This cannot be localhost
          # or 127.0.0.1 for non-Docker templates!
          - name: CODER_ACCESS_URL
            value: "http://pibox.local/code"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: code-server
spec:
  selector:
    app: code-server
    tier: frontend
  ports:
    - name: "http"
      port: 80
      targetPort: "http"
      protocol: TCP