apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: code-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: code-server
      tier: frontend
  template:
    metadata:
      labels:
        app: code-server
        tier: frontend
    spec:
      containers:
      - image: ghcr.io/coder/coder:latest
        name: code-server
        ports:
        - containerPort: 7000
        env:
          - name: CODER_PG_CONNECTION_URL
            value: "postgresql://username:password@code-server/code-db.code-server.svc.cluster.local?sslmode=disable"
          - name: CODER_ADDRESS
            value: "0.0.0.0:7080"
          # You'll need to set CODER_ACCESS_URL to an IP or domain
          # that workspaces can reach. This cannot be localhost
          # or 127.0.0.1 for non-Docker templates!
          - name: CODER_ACCESS_URL
            value: "http://pibox.local/code"
          # Alternatively, you can enable CODER_TUNNEL for
          # proof-of-concept deployments.
          - name: CODER_TUNNEL
            value: "false"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"