apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-server-ingress
  namespace: code-server
spec:
  entryPoints:
    - websecure           
  routes:           # v-- adding a host rule
    - match: Host(`code.ls.local`)
      kind: Rule
      priority: 7 # <-- makes this take precedence over argo
      services:
        - name: code-server
          namespace: code-server
          port: 8080
  tls:
    certResolver: default